### PR TITLE
Making pull request.......

### PR DESCRIPTION
**Pull request by Radical-from-Scratch**
See the commit change for new Squeak instructions

### CODE REVIEW

**Comment by Jonathan50** [comment]
Nice title. Seriously, what is this?

**Comment by Radical-from-Scratch** [comment]
It's a pull request for the whiskers project.  The reason it's so vague is being most of the info is in pull request 4, not 6.

**Comment by Jonathan50** [comment]
Oh cool I didn't know about reactions. But why the downvote? And #4 also has a cryptic title.

**Comment by Radical-from-Scratch** [comment]
Because I didn't really like it. Also, I rather meant the long version of the title as in "Squeak didn't give me a changes file--so I'll hand-tell you what's changed. First off, in the "open" menu it now says Whiskers (though I may have accidentally written Explore, another mod I work on :P ) and going into Squeak is now by shift-clicking the stop sign."

**Comment by Jonathan50** [comment]
Why the downvote?

**Comment by Radical-from-Scratch** [comment]
Read the first sentence of my above comment.

**Comment by Jonathan50** [comment]
I meant why did you downvote
> Oh cool I didn't know about reactions. But why the downvote? And #4 also has a cryptic title.

**Comment by NoMod-Programming** [comment]
Hmm... I can't seem to enter development mode on a mac... Also, I don't know what you mean by "the open menu having Whiskers". Maybe you can upload a screenshot explaining that?

**Comment by Radical-from-Scratch** [comment]
Uh oh.....I forgot about how to do it on a Mac. For now, I will make it so that it *always* opens if running a mac, but will look into that for the future.

**Comment by Radical-from-Scratch** [comment]
What I meant by the open menu saying Whiskers, is, okay. you're in Squeak and you click on the white, then you click open. The last line will say WHISKSERS, not Scratch.

**Pull request closed without merging**
