### PR TITLE
We want people to think 2.0 thoughts, not 2.8 ones

### PR DESCRIPTION
**Pull request by Radical-from-Scratch**

### CODE REVIEW

**Comment by Radical-from-Scratch** [comment]
BTW, you need to create an SH file in the runtime folder and type this: 

#! /bin/sh
rundir=`dirname "$0"`
userdir=`pwd`
cd "${rundir}"
if [[ "x$1" == "x" ]]; then arg="dev" ; elif [[ "${1:0:1}" == "/" || \
       "${1:0:1}" == "~" ]] ; then \
     arg="$1" ; else arg="${userdir}/$1" ; fi
if [[ "${arg}" != "dev" && \
      `basename "${arg}"` == `basename "${arg}" .ypr` && \
      `basename "${arg}"` == `basename "${arg}" .sb` ]]; then \
   arg="${arg}.ypr" ; fi
Scratch.app/Contents/MacOS/Scratch Whiskers.image "${arg}" dev "${arg}" 2> /dev/null &

**Comment by Jonathan50** [comment]
please use code blocks

**Comment by Radical-from-Scratch** [comment]
?

**Comment by Jonathan50** [comment]
Use three backticks and then \(optionally\) the language name so it's in monospace.
e.g
```sh
#! /bin/sh
rundir=dirname "$0"
userdir=pwd
cd "${rundir}"
if [[ "x$1" == "x" ]]; then arg="dev" ; elif [[ "${1:0:1}" == "/" || \
"${1:0:1}" == "~" ]] ; then \
arg="$1" ; else arg="${userdir}/$1" ; fi
if [[ "${arg}" != "dev" && \
basename "${arg}" == basename "${arg}" .ypr && \
basename "${arg}" == basename "${arg}" .sb ]]; then \
arg="${arg}.ypr" ; fi
Scratch.app/Contents/MacOS/Scratch Whiskers.image "${arg}" dev "${arg}" 2> /dev/null &
```

**Comment by Radical-from-Scratch** [comment]
What's a backtick? Is it ' or \ or ` or what?

**Comment by Jonathan50** [comment]
It's \`.
\(Check out https://guides.github.com/features/mastering-markdown/)

**Comment by Jonathan50** [comment]
\`\`\`langname
\`\`\`

**Pull request merged**
