### PR TITLE
This might be corrupt just try it

### PR DESCRIPTION
**Pull request by Radical-from-Scratch**

### CODE REVIEW

**Comment by Radical-from-Scratch** [comment]
Squeak didn't give me a changes file--so I'll hand-tell you what's changed. First off, in the "open" menu it now says Whiskers (though I may have accidentally written Explore, another mod I work on :P ) and going into Squeak is now by shift-clicking the stop sign.

**Comment by NoMod-Programming** [comment]
Nope. It's corrupted :package:

**Comment by NoMod-Programming** [comment]
Maybe try using the [url=https://desktop.github.com/]Github Client[/url] to upload it?

**Comment by Radical-from-Scratch** [comment]
I have it installed, I'll try it out.

**Comment by Radical-from-Scratch** [comment]
Just to clarify, I already had it installed, but it didn't occur to me to use it.

**Pull request closed without merging**
